# Generated by Django 3.1.7 on 2021-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_address_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Ikeja', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.TextField(default='Nigeria', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='country_code',
            field=models.TextField(default='NG', max_length=4),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default='1.000055555', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default='2.59595959', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.FloatField(default='100001', max_length=9),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Lagos', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.TextField(default='No 58B', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.CharField(default='morison crescent', max_length=250),
        ),
    ]
