# Generated by Django 3.1.7 on 2021-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210610_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='type',
            field=models.CharField(default='lmp636', max_length=100),
        ),
    ]
